### ISSUE TITLE
[suggestions] managing deps with bower

### ISSUE THREAD

**Issue by leesei** [dtao/slidedown#2]
Thanks for the effort in putting this up. It is _THE easiest_ solution for making a presentation form Markdown I've ever see.

I see that there are several dependencies for this project.  
Any plans to use [`bower`](http://bower.io/) to manage them?

**Comment by dtao** [comment]
Yeah, that's not a bad idea. Right now I'm using browserify to include all dependencies in one file (slidedown.build.js), but I don't actually really like that approach very much. What I'm thinking of doing instead if having slidedown.js only optionally include parts (e.g., highlight.js) and still work without them. That's what it already does with hammer.js, actually. I don't think I can quite get around the marked dependency, though; so yes, I have no problem with adding a bower.json to the mix.

**Comment by leesei** [comment]
I spotted the `deft.json` after posting the issue.
From your response I suppose you use it to pull the dependencies into `lib/` and browerify them.
Using deft rather than bower seems fine for me.
But why not also pulling `marked` with it? Is it a deft issue?

slidedown is a neat client side solution for showing Markdown. 
I think using browserify to build it is justified.
Can you also share the project that build slidedown.build.js? This repo can be used for keeping the release and demo page.
