### ISSUE TITLE
New organization for slidedown

### ISSUE THREAD

**Issue by leesei** [dtao/slidedown#5]
Hi Dan

My friend @cyrusn has added several features to [slidedown](https://github.com/cyrusn/slidedown).
I also have some idea to re-factor it.
Here's the [todo](http://cyrusn.github.io/slidedown/?src=md/todo.md).

Since the tree structure would be quite different (I could add more docs for the refactoring if you wish).
I'm thinking of starting a organization "slidedown" for this project.
We'll prepare the restructured tree first. All three of us could contribute.

What do you think? :wink:

**Comment by dtao** [comment]
Sounds good to me!

I kinda would have liked for slidedown/slidedown to be a fork of dtao/slidedown, just for attribution purposes... but it ain't no big deal.

I'll happily update the README in this repo to point to that one once it's off to a good start.

**Comment by leesei** [comment]
Thanks for your green light.

Of course I would attribute you as the original author.
But I would like to split the current two branch into two repos (slidedown/slidedown and slidedown/slidedown.github.io). I'm inclined to starting afresh.

And I just noticed dtao/slidedown was missing a license.
Is it okay to slidedown/slidedown with MIT?

**Comment by dtao** [comment]
Certainly OK with me.
